name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@vlatest
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@latest

    - name: setup 
      run: |
        luarocks install busted

    - name: test
      run: |
        busted -o utfTerminal
